Test macOS build

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2711,19 +2711,19 @@ _ACEOF
 fi
 
 
-if test "x$ac_cv_lib_gsl_gsl_blas_dgemm" != xyes; then
-    echo "------------------------- LIBGSL ERROR ------------------------------"
-    echo "Configuration failed because libgsl was not found. Try installing:"
-    echo " * deb: libgsl-dev (Debian, Ubuntu, etc)"
-    echo " * rpm: gsl-devel (Fedora, CentOS, RHEL)"
-    echo " * csw: gsl_dev (Solaris)"
-    echo "If libgsl is already installed, check that 'pkg-config' is in your"
-    echo "PATH and PKG_CONFIG_PATH contains a libgsl .pc file. If pkg-config"
-    echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
-    echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
-    echo "--------------------------------------------------------------------"
-  exit 1;
-fi
+#if test "x$ac_cv_lib_gsl_gsl_blas_dgemm" != xyes; then
+#    echo "------------------------- LIBGSL ERROR ------------------------------"
+#    echo "Configuration failed because libgsl was not found. Try installing:"
+#    echo " * deb: libgsl-dev (Debian, Ubuntu, etc)"
+#    echo " * rpm: gsl-devel (Fedora, CentOS, RHEL)"
+#    echo " * csw: gsl_dev (Solaris)"
+#    echo "If libgsl is already installed, check that 'pkg-config' is in your"
+#    echo "PATH and PKG_CONFIG_PATH contains a libgsl .pc file. If pkg-config"
+#    echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
+#   echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
+#   echo "--------------------------------------------------------------------"
+#  exit 1;
+#fi
 
 ## credits to Dirk Eddelbuettel and RcppGSL
 # Extract the first word of "gsl-config", so it can be a program name with args.
